//
//  LoremIpsumData.swift
//  UtilKB
//
//  Created by An So on 2025-05-13.
//

let loremIpsum: [String] = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet tincidunt leo. Ut sit amet augue rhoncus lorem cursus congue. Nullam id vestibulum elit. In sed malesuada arcu, quis luctus mauris. Morbi nec laoreet magna. Maecenas id ullamcorper magna. Curabitur tempus neque in nisl venenatis, in accumsan enim feugiat. Curabitur pulvinar eros suscipit condimentum vehicula. Pellentesque quis finibus dolor. Praesent quis sapien vestibulum, mollis purus et, sagittis orci. Maecenas vel quam non neque facilisis rhoncus.",
  "Nullam sit amet ligula sed leo hendrerit varius. Nam consectetur mauris eget facilisis gravida. Sed iaculis eget tellus nec ultrices. Proin dictum justo eu metus sagittis euismod. Duis ultricies porta pharetra. Suspendisse feugiat, sapien ac tincidunt malesuada, lorem massa auctor mauris, vel porta quam nisl eget erat. Donec nunc urna, hendrerit sed sem vitae, egestas maximus nulla. Mauris non orci feugiat, eleifend orci vel, faucibus lacus. Nam suscipit, nibh vitae pharetra facilisis, sem velit accumsan nisi, luctus tincidunt felis nunc ut orci. Praesent faucibus turpis ut sem iaculis ultricies. Etiam quis vehicula nisl.",
  "Proin quam ligula, vestibulum at justo quis, mollis scelerisque mi. Phasellus massa nisi, egestas at velit in, tincidunt volutpat lectus. Integer et tincidunt augue. Aliquam tempus, tortor et placerat mollis, lorem neque consequat turpis, sed venenatis est ex ut lacus. Vestibulum in bibendum ex. Ut finibus nibh elit, sit amet consectetur nibh scelerisque eu. Nunc molestie ultrices tellus at posuere. Aliquam in luctus quam. Aliquam nisi sapien, tempor sed nunc non, tristique ornare sem. Vivamus in aliquam arcu. Nunc non tempus enim. Proin et gravida velit. Nulla rutrum dapibus vestibulum. Vivamus dapibus dictum consectetur. Integer a nibh sit amet dolor dignissim laoreet sit amet eu dolor. Nulla pharetra nunc in tortor euismod, at hendrerit mi euismod.",
  "Pellentesque urna lectus, mollis a dapibus eu, laoreet tincidunt lectus. Nunc at lacinia risus. Phasellus dictum arcu eget eros consectetur, sed elementum quam fringilla. In hac habitasse platea dictumst. Vestibulum in orci aliquet, tempor enim quis, consectetur ante. In in urna tempor, sodales purus sit amet, dictum enim. Sed non congue dui, a rhoncus metus. Quisque sollicitudin, metus sed placerat mattis, sem leo blandit nibh, eget efficitur dolor leo non ex. Nam hendrerit varius dictum. Proin sit amet urna quam.",
  "Nam porta nulla lacus, sit amet fringilla velit gravida quis. Mauris erat orci, tincidunt eget nulla in, volutpat sollicitudin ante. Proin tincidunt arcu metus, et venenatis velit cursus vitae. Donec porttitor ac lorem id dignissim. Morbi posuere erat at urna varius tincidunt. Vestibulum eget arcu ut odio lobortis placerat at id magna. Duis fermentum sagittis libero, in blandit eros tempus sit amet. Curabitur semper, diam et condimentum congue, magna felis rhoncus enim, sed placerat neque dolor sed purus. Etiam quis enim nec erat fringilla dapibus id et mi. Donec iaculis sagittis purus. Vivamus volutpat egestas dapibus. Donec id metus sit amet mi gravida egestas sit amet non elit. Integer fermentum sem at ex consequat, in viverra dui imperdiet. ",
].map({ p in
  return p.lowercased()
})
